name: flutboard
description: A FlipBoard like Flutter application

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.18.0
  shared_preferences: ^0.4.2
  url_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/1x1_transparent.png
    - assets/images/flutboard_logo.png
