name: flutter_board
description: A FlipBoard Flutter clone

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flip_panel: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/data/articles.json
    - assets/images/1x1_transparent.png
    - assets/images/flutter_logo.png
